# Generated by Django 3.1.3 on 2023-08-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230808_0022'),
    ]

    operations = [
    ]
